### PR TITLE
Passing objective as an argument to mission

### PR DESCRIPTION
**Pull request by mayork**
@1ozturkbe I made the script to automate the computation of that table. It required making the varkey of the objective an argument to mission and the class inside `SP_aircraft.py`...let me know what you think.

### CODE REVIEW

**Comment by 1ozturkbe** [comment]
But the tests are failing? We should fix those.

**Comment by mayork** [comment]
I can fix once I'm but not until the 19th (don't have my computer here)...the tests are failing because the objective isn't passed as an argument where the tests are run

**Comment by 1ozturkbe** [comment]
Lol I can fix and merge at the first opportunity. May take some time though.

**Comment by 1ozturkbe** [comment]
Tests good. Killer plots good. Merging.

**Comment by mayork** [comment]
Sweet thanks! This makes generating that table of different objectives exponentially easier

**Comment by 1ozturkbe** [comment]
Glad! Deleting branch.

**Pull request merged**
